import type { Metadata } from "next";
import LegalPage from "../components/legal/LegalPage";
import { SchemaScript } from "../components/SchemaScript";
import { BUSINESS_EMAIL, BUSINESS_NAME, BUSINESS_URL } from "@/lib/business-config";
import { generateBreadcrumbSchema, generateWebPageSchema } from "@/lib/schema";

const PAGE_URL = `${BUSINESS_URL}/privacy`;
const LAST_UPDATED = "2026-09-30T00:00:00+05:30";
const LAST_UPDATED_LABEL = "September 30, 2026";
const PAGE_DESCRIPTION =
  "Read how Regenis Life collects, uses, stores, and protects personal information submitted through equipment enquiries and website interactions.";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: PAGE_DESCRIPTION,
  alternates: { canonical: "/privacy" },
  openGraph: {
    title: "Privacy Policy | Regenis Life",
    description: PAGE_DESCRIPTION,
    url: "/privacy",
    type: "website",
    images: [{ url: "/Regenis.png", alt: "Regenis Life" }],
  },
};

export default function PrivacyPage() {
  const webPageSchema = generateWebPageSchema({
    name: "Regenis Life Privacy Policy",
    url: PAGE_URL,
    description: PAGE_DESCRIPTION,
    pageType: "WebPage",
    isPartOf: { name: BUSINESS_NAME, url: BUSINESS_URL },
    dateModified: LAST_UPDATED,
    about: { "@id": `${BUSINESS_URL}/#organization` },
  });
  const breadcrumbSchema = generateBreadcrumbSchema([
    { label: "Home", url: BUSINESS_URL },
    { label: "Privacy Policy", url: PAGE_URL },
  ]);

  return (
    <>
      <SchemaScript id="privacy-schema" schema={[webPageSchema, breadcrumbSchema]} />
      <LegalPage
        title="Privacy Policy"
        description={PAGE_DESCRIPTION}
        updatedLabel={LAST_UPDATED_LABEL}
        currentPath="/privacy"
      >
        <p>
          This Privacy Policy explains how {BUSINESS_NAME} collects and handles personal
          information when you visit this website, contact us, or submit an equipment
          enquiry. It applies to information collected through regenis.life and related
          communications with our team.
        </p>

        <h2>Information we collect</h2>
        <p>Depending on how you interact with the website, we may collect:</p>
        <ul>
          <li>Your name, professional or organisation details, email address, and phone number.</li>
          <li>The equipment or product category you are interested in.</li>
          <li>Information you include in an enquiry or subsequent communication.</li>
          <li>Basic technical information such as browser type, device type, referring page, and website activity when generated by our hosting, security, or measurement services.</li>
        </ul>
        <p>
          Please do not submit patient records, diagnostic reports, or other sensitive health
          information through the general enquiry form.
        </p>

        <h2>How we use information</h2>
        <p>We may use personal information to:</p>
        <ul>
          <li>Respond to equipment, pricing, availability, installation, or training enquiries.</li>
          <li>Understand your facility requirements and arrange relevant follow-up.</li>
          <li>Maintain business records and manage our relationship with you.</li>
          <li>Operate, secure, troubleshoot, and improve the website.</li>
          <li>Meet legal, regulatory, accounting, or fraud-prevention obligations.</li>
        </ul>
        <p>
          Where consent is the appropriate basis for processing, you may withdraw it by
          contacting us. Withdrawal does not affect processing already completed lawfully.
        </p>

        <h2>How information may be shared</h2>
        <p>
          We may share relevant information with service providers that support website
          hosting, enquiry management, communications, security, or professional advice.
          When necessary to answer a product-specific enquiry, we may also share relevant
          business contact details with the applicable manufacturer or authorised partner.
          We do not sell personal information.
        </p>
        <p>
          Information may also be disclosed when required by law, regulation, court order,
          or a lawful request from a public authority, or when reasonably necessary to
          protect rights, safety, and security.
        </p>

        <h2>Retention and security</h2>
        <p>
          We retain personal information only for as long as reasonably required for the
          purpose for which it was collected, for legitimate business records, or to satisfy
          applicable legal obligations. We use reasonable administrative and technical
          safeguards, but no internet transmission or storage system can be guaranteed to be
          completely secure.
        </p>

        <h2>Cookies and similar technologies</h2>
        <p>
          The website and its hosting providers may use cookies or similar technologies that
          are necessary for functionality, security, and performance. If optional analytics
          or marketing technologies are introduced, we will update this policy and provide
          any consent choices required by applicable law.
        </p>

        <h2>Your choices and rights</h2>
        <p>
          Subject to applicable law, you may ask for access to or correction of your personal
          information, request deletion where appropriate, withdraw consent, or raise a
          concern about how your information is handled. We may need to verify your identity
          before acting on a request.
        </p>

        <h2>Children’s privacy</h2>
        <p>
          This website is intended for professional and business audiences and is not
          directed to children. We do not knowingly seek personal information from children
          through the equipment enquiry forms.
        </p>

        <h2>Third-party websites</h2>
        <p>
          Links to manufacturers, social networks, or other third-party websites are provided
          for convenience. Their privacy practices are governed by their own policies, not
          this Privacy Policy.
        </p>

        <h2>Updates and contact</h2>
        <p>
          We may update this policy when our website, services, or legal obligations change.
          The current version will remain available on this page with its latest revision
          date. For a privacy request or question, email us at{" "}
          <a href={`mailto:${BUSINESS_EMAIL[0]}`}>{BUSINESS_EMAIL[0]}</a>.
        </p>
      </LegalPage>
    </>
  );
}
